### ISSUE TITLE
Questions on your dataset

### ISSUE THREAD

**Issue by simonsoubeyrand** [brainhack-school2020/johnaldmcfist-neonatalNiPype#2]
Don't know a lot on the subject, but would there be a way, after finishing your pipeline, to validate it on a different data sets than yours? Do you know if there's any one (BIDS-friendly) that's available out there?

Cheers,
S.

**Comment by johnaldmcfist** [comment]
Depending on the pipeline it can be done but the main issue here would be the data collection itself. There are not many infant MRI datasets. My main goal with this project is to shift my analysis to a "more reproducible" workflow which I can tweak easily to try out different techniques.
